server:
  port: 8686
spring:
  profiles:
    active: dev
  application:
    name: blog-eureka
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
eureka:
  client:
    register-with-eureka: false #是否将自己注册到eureka中
    fetch-registry: false #是否从eureka中获取信息
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
