spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.194.235:3306/PersonalBlog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B9
    username: root
    password: ljkwlc1016
  redis:
    host: 139.224.194.235
    password: ljkwlc1016

logging:
  level:
    root: warn
    com.kun98.server: debug
  file:
    path: log/blog-prod.log
eureka:
  client:
    service-url:
      defaultZone: http://139.224.194.235:8686/eureka/
  instance:
    prefer-ip-address: true
