server:
  port: 9002

spring:
  application:
    name: blog-server
  redis:
    host: 127.0.0.1
    password: ljkwlc1016

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/PersonalBlog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B9
    username: root
    password: ljkwlc1016
    type: com.alibaba.druid.pool.DruidDataSource
  aop:
    proxy-target-class: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.kun98.common.po
  global-config:
    #    db-config:
    #      table-prefix: t_
    id-type: 1  #0:数据库ID自增   1:用户输入id
    #    db-column-underline: false
    #    db-config:
    #          table-underline=false:
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    #  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

enable:
  swagger2: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8686/eureka/
  instance:
    prefer-ip-address: true

